### ISSUE TITLE
Benchmarks fail to build with GHC 9.14

### ISSUE THREAD

**Issue by hasufell** [haskell/os-string#40]
@TeofilC 

https://github.com/haskell/os-string/actions/runs/21213238240/job/61027132112#step:5:420

```
[3 of 4] Compiling BenchWindowsString ( bench/BenchWindowsString.hs, dist-newstyle/build/host/x86_64-linux/ghc-9.14.1/os-string-2.0.9-bench/build/bench/bench-tmp/BenchWindowsString.o )
bench/Common.hs:42:14: error: [GHC-87897]
    • Exception when trying to run compile-time code:
        Systen.OsString.Common.pstr: no Template Haskell
      Code: ghc-internal-9.1401.0:GHC.Internal.TH.Quote.quoteExp
              pstr
              "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis\n\
              \nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\
              \Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu\n\
              \fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in\n\
              \culpa qui officia deserunt mollit anim id est laborum."
    • In the quasi-quotation:
        [pstr|incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.|]
   |
42 | loremIpsum = [OSSTR|incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
